public class Main
{
	public static void main(String[] args) {
		tester.recursiveprint(1);
	}
}
class tester{
    public static void recursiveprint(int num){
        System.out.println("number: "+num);
        if(num==0) return;else
        recursiveprint(++num);
    }
}
///////////////check exception
public class Main
{
	public static void main(String[] args) {
		try{
		    int x=0;
		    int y=50/x;
		    System.out.println("y = "+y);
		}
		catch(ArithmeticException e){
		    System.out.println("Division by zero");
		}
		System.out.println("After catch statement");
	}
}
/////////////
public class Main
{
	public static void main(String[] xyz) {
		try{
		    for (int i=0; i<=xyz.length;i++ ){ 
		        System.out.println(xyz[i]);
		    }
		}
		catch(ArrayIndexOutOfBoundsException e){
		    System.out.println("Array Index is Out Of Bounds");
		}
		System.out.println("thank you");
	}
}
///////////
public class Main
{
	public static void main(String[] xyz) {
		try{
		    int x=10;
		    int y=0;
		    System.out.println("z = "+x/y);
		}
		catch(ArithmeticException e){
		    System.out.println("Division by zero");
		}
		System.out.println("After catch statement");
	}
}
////////////
public class Main
{
	public static void main(String[] args) {
		try{
		    int x=100;
		    int y=0;
		    int z=x/y;
		    System.out.println(args[1]);
		}
		catch(ArithmeticException e){
		    System.out.println("Division by zero");
		}
		catch(ArrayIndexOutOfBoundsException ar){
		    System.out.println("Array Index is Out Of Bounds");
		}
	}
}
//////////////
public class Main
{
	public static void main(String[] args) {
		try{
		    int x=100;
		    int y=0;
		    int z=x/y;
		    System.out.println(args[1]);
		}
		catch(Exception e){
		    System.out.println("oops something went wrong ðŸ¥² because of "+e);
		}
	}
}
///////////